// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsxca_QJ5SczI6e35YiL_fyHOOSOIZhM',
    appId: '1:241029721520:web:3d9ed83182c164c8727a75',
    messagingSenderId: '241029721520',
    projectId: 'fooddelightapp',
    authDomain: 'fooddelightapp.firebaseapp.com',
    storageBucket: 'fooddelightapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdrrfLBxYfRosNtoPirt8Mhfq7HxpUxGQ',
    appId: '1:241029721520:android:6a4d3d48818d7f8e727a75',
    messagingSenderId: '241029721520',
    projectId: 'fooddelightapp',
    storageBucket: 'fooddelightapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGsxca_QJ5SczI6e35YiL_fyHOOSOIZhM',
    appId: '1:241029721520:web:a15bb569d62d5ac8727a75',
    messagingSenderId: '241029721520',
    projectId: 'fooddelightapp',
    authDomain: 'fooddelightapp.firebaseapp.com',
    storageBucket: 'fooddelightapp.firebasestorage.app',
  );
}
